#########################################
###          Main App config          ###
#########################################
template_version: 1

# Main server app name
app_name: rogerthat

# Rebroadcast last received event on websocket first connection.
# Recommended to keep this on in case events are missed during a network drop out.
rebroadcast_on_ws_connect: true

# Enabled debug mode
debug_mode: false
