name: Docker Image CI

on:
  push:
    branches: [ "master", "mqtt" ]
  pull_request:
    branches: [ "master", "mqtt" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rogerthat:$(date +%s)
    - name: Install pre_commit
      if: ${{inputs.program-cache-hit}} != 'true' || ${{inputs.dependencies-cache-hit}} != 'true'
      shell: bash
      run: |
        conda install -c conda-forge pre_commit
    - name: Install RogerThat
      if: ${{inputs.dependencies-cache-hit}} != 'true'
      shell: bash -l {0}
      run: |
        ./scripts/update_environment.sh
    - name: Run pre-commit hooks on diff
      shell: bash
      if: steps.program-changes.outputs.cache-hit != 'true' || steps.conda-dependencies.outputs.cache-hit != 'true'
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate rogerthat
        pre-commit run --files $(git diff --name-only origin/$GITHUB_BASE_REF)
